refactor: Change to `match` rather than map_err
This fixes the first error but we still have the critical error:

 wink@3900x 23-02-20T23:57:59.886Z:~/prgs/rust/myrepos/exper_ownership_of_managed_things (main)
 $ cargo build
    Compiling exper_ownership_of_managed_things v0.1.0 (/home/wink/prgs/rust/myrepos/exper_ownership_of_managed_things)
 error[E0502]: cannot borrow `ae.bi_dir_channels_vec` as mutable because it is also borrowed as immutable
    --> src/lib.rs:201:33
     |
 201 | ...                   ae.bi_dir_channels_vec.push(bdlcs);
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mutable borrow occurs here
 202 | ...                   let x = ae.bi_dir_channels_vec.get(actor_idx).unwrap();
     |                               ------------------------------------- immutable borrow occurs here
 ...
 207 | ...                   selector.recv(x.our_channel.get_recv());
     |                       --------------------------------------- immutable borrow later used here

 For more information about this error, try `rustc --explain E0502`.
 error: could not compile `exper_ownership_of_managed_things` due to previous error