wip: Compile error can't use sent Actor
I've sent the Box<dyn Actor> over a channel, but then need to save it
in ActorExecutor so messages can be sent to it. I get the following
compile error:

 $ cargo test -- --nocapture
    Compiling exper_ownership_of_managed_things v0.1.0 (/home/wink/prgs/rust/myrepos/exper_ownership_of_managed_things)
 error[E0507]: cannot move out of `msg.actor` which is behind a shared reference
    --> src/lib.rs:172:37
     |
 172 | ...                   let a = msg.actor;
     |                               ^^^^^^^^^
     |                               |
     |                               move occurs because `msg.actor` has type `Box<dyn Actor>`, which does not implement the `Copy` trait
     |                               help: consider borrowing here: `&msg.actor`

 For more information about this error, try `rustc --explain E0507`.
 error: could not compile `exper_ownership_of_managed_things` due to previous error
 warning: build failed, waiting for other jobs to finish...
 error: could not compile `exper_ownership_of_managed_things` due to previous error